### ISSUE TITLE
wmi

### ISSUE THREAD

**Issue by ddkwork** [tandasat/DotNetHooking#1]
how to hook wmi-->win32processid with this tool?

**Comment by tandasat** [comment]
I do not find "win32processid" exactly and not sure if I understand your question really, but you could inspect invocation of WMI from C# by hooking methods of classes that implement such interfaces (eg. ManagementBaseObject etc).

**Comment by ddkwork** [comment]
sorry,is this:
https://msdn.microsoft.com/en-us/library/aa394372(v=vs.85).aspx

**Comment by tandasat** [comment]
Yup. You can hook C# methods that access that WMI class.  ManagementBaseObject is one of such classes.

**Comment by ddkwork** [comment]
it will be cool but i do not known how to debug c# for the wmi:Win32_Process->ProcessId created code with the VS2015,can you make a simple?

**Comment by tandasat** [comment]
If you are not comfortable with debugging and reverse engineering managed code, I would recommend you to spend some time to familiarize your self with it. When you got clearer ideas of what you need to do for with hooking after some exploration of C# and WMI, and still have questions, I am happy to help you :)
